from enum import StrEnum


class TitleSource(StrEnum):
    DEFAULT = "DEFAULT"
    AUTO_FIRST_MESSAGE = "AUTO_FIRST_MESSAGE"
    USER_EDIT = "USER_EDIT"


class BranchPointType(StrEnum):
    ROOT = "ROOT"
    USER_MESSAGE_EDIT = "USER_MESSAGE_EDIT"
    ANSWER_VERSION_ACTIVATE = "ANSWER_VERSION_ACTIVATE"


class BranchStatus(StrEnum):
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"


class UserMessageStatus(StrEnum):
    PENDING = "PENDING"
    HAS_ACTIVE_ANSWER = "HAS_ACTIVE_ANSWER"
    GENERATION_FAILED = "GENERATION_FAILED"


class AnswerVersionStatus(StrEnum):
    GENERATING = "GENERATING"
    SUCCEEDED_ACTIVE = "SUCCEEDED_ACTIVE"
    SUCCEEDED_INACTIVE = "SUCCEEDED_INACTIVE"
    FAILED = "FAILED"
    STOPPED = "STOPPED"


class SelectionMode(StrEnum):
    AUTO_ROUTE = "AUTO_ROUTE"
    AUTO_FALLBACK = "AUTO_FALLBACK"
    USER_SELECTED = "USER_SELECTED"


class GenerationStatus(StrEnum):
    IDLE = "IDLE"
    PREPARING_CONTEXT = "PREPARING_CONTEXT"
    SEARCHING = "SEARCHING"
    ROUTING = "ROUTING"
    GENERATING = "GENERATING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"


class SearchStatus(StrEnum):
    SUCCESS_WITH_RESULTS = "SUCCESS_WITH_RESULTS"
    SUCCESS_NO_VALID_RESULTS = "SUCCESS_NO_VALID_RESULTS"
    FAILED = "FAILED"
    TIMEOUT = "TIMEOUT"


class GenerationMode(StrEnum):
    NEW_MESSAGE = "NEW_MESSAGE"
    REGENERATE = "REGENERATE"


class RegenerationMode(StrEnum):
    REGENERATE_ORIGINAL_MODEL = "REGENERATE_ORIGINAL_MODEL"
    REGENERATE_AUTO_ROUTE = "REGENERATE_AUTO_ROUTE"
    REGENERATE_USER_SELECTED = "REGENERATE_USER_SELECTED"


class AttemptStatus(StrEnum):
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"


class ErrorCategory(StrEnum):
    TRANSIENT_TIMEOUT = "TRANSIENT_TIMEOUT"
    TRANSIENT_NETWORK = "TRANSIENT_NETWORK"
    TRANSIENT_RATE_LIMIT = "TRANSIENT_RATE_LIMIT"
    TRANSIENT_SERVER = "TRANSIENT_SERVER"
    MODEL_REQUEST_REJECTED = "MODEL_REQUEST_REJECTED"
    MODEL_RESPONSE_INVALID = "MODEL_RESPONSE_INVALID"
    MODEL_UNAVAILABLE = "MODEL_UNAVAILABLE"
    GLOBAL_INPUT_VIOLATION = "GLOBAL_INPUT_VIOLATION"
    UNKNOWN = "UNKNOWN"


class MemoryVersionType(StrEnum):
    INITIAL_SYSTEM_SUMMARY = "INITIAL_SYSTEM_SUMMARY"
    INCREMENTAL_SYSTEM_UPDATE = "INCREMENTAL_SYSTEM_UPDATE"
    USER_EDIT = "USER_EDIT"
    RESTORE = "RESTORE"
    BRANCH_INHERIT = "BRANCH_INHERIT"


class MemoryUpdateStatus(StrEnum):
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"


class MemoryOperationStatus(StrEnum):
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
